name: Backend Deploy

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.5

      - name: Install dependencies
        run: npm install  

      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: dev.reqspark.com
          username: deploy
          key: ${{ secrets.SSH_KEY }}
          source: "*" 
          target: ${{ github.ref == 'refs/heads/main' && '/var/www/mcp.prod/backend' || '/var/www/mcp.dev/backend' }}

      - name: Restart Backend
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: dev.reqspark.com
          username: deploy
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ github.ref == 'refs/heads/main' && '/var/www/mcp.prod/backend' || '/var/www/mcp.dev/backend' }}
            npm install --production

            PM2_CMD=pm2

            $PM2_CMD describe ${{ github.ref == 'refs/heads/main' && 'backend-prod' || 'backend-dev' }} || \
            $PM2_CMD start server.js --name ${{ github.ref == 'refs/heads/main' && 'backend-prod' || 'backend-dev' }} -- -p ${{ github.ref == 'refs/heads/main' && '3002' || '3003' }}

            $PM2_CMD restart ${{ github.ref == 'refs/heads/main' && 'backend-prod' || 'backend-dev' }}
